name:                type-machine
version:             0.1.0.0
github:              "Arthi-chaud/type-machine"
license:             BSD-3-Clause
author:              "Arthi-chaud"
maintainer:          "aj530@kent.ac.uk"
copyright:           "2025 Arthi-chaud"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Template Haskell-based Type functions on record types in Haskell
category:            Types 

description:         Please see the README on GitHub at <https://github.com/Arthi-chaud/type-machine#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- template-haskell
- syb

default-extensions:
- TemplateHaskell
- LambdaCase
- TupleSections
- RankNTypes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  vector-example:
    source-dirs: examples
    main: Vector.hs
    dependencies:
    - type-machine

library:
  source-dirs: src
  dependencies:
  - mtl
  exposed-modules:
  - TypeMachine
  - TypeMachine.Functions
  - TypeMachine.TM
  - TypeMachine.Type
  - TypeMachine.TM.Syntax
  - TypeMachine.Log
  - TypeMachine.TH
  - TypeMachine.TH.Is

tests:
  type-machine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-unused-top-binds
    dependencies:
    - type-machine
    - hspec
