snapshot: nightly-2025-01-14

packages:
- .

extra-deps:
- extensible-0.9.2
- hashable-1.4.7.0
# Note: too old
# - record-0.4.2
- basic-lens-0.0.2
# - transformers-0.5.6.2
# Note: The OG superrecord is not maintained
# So we use this fork that is compatible with newer ghc versions 
# https://github.com/agrafix/superrecord/pull/35
- github: possehl-analytics/superrecord 
  commit: 5a7d6867c6c2a182f25ac5ebb9f2b193218f2b13
system-ghc: true
# allow-newer: true
# allow-newer-deps: 
#   - record
